version: "3.9"

services:
  landing:
    build:
      context: .
      args:
        ENV_FILE: .env.stg
    container_name: landing_stg
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.stg
    environment:
      NODE_ENV: staging
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: landing_stg_db
    restart: always
    environment:
      POSTGRES_USER: payload
      POSTGRES_PASSWORD: payloadpass
      POSTGRES_DB: payloaddb
    volumes:
      - ./data/stg-db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
