version: "3.9"
services:
  landing:
    build: .
    container_name: landing
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    environment:
      NODE_ENV: production
