version: "3.9"

services:
  landing:
    build: .
    container_name: landing_stg
    restart: always
    ports:
      - "3001:3000"
    env_file:
      - .env.stg
    environment:
      NODE_ENV: production
