version: "3.9"

services:
  landing:
    build:
      context: .
      args:
        ENV_FILE: .env.stg
    container_name: landing_stg
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.stg
    environment:
      NODE_ENV: staging
    volumes:
      - ./data/stg:/app/data
