version: "3.9"

services:
  landing:
    build:
      context: .
      args:
        ENV_FILE: .env.prod
    container_name: landing
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    environment:
      NODE_ENV: production
    volumes:
      - ./data/prod:/app/data