import type { Block } from 'payload'

export const PlanSummaryCard: Block = {
  slug: 'planSummaryCard',
  interfaceName: 'PlanSummaryCardBlock',
  labels: { singular: 'Plan Summary Card', plural: 'Plan Summary Cards' },
  fields: [
    {
      name: 'sectionTitle',
      type: 'text',
      label: 'Section title',
      localized: true,
      admin: { placeholder: 'Your selection' },
    },
    {
      name: 'planVariant',
      type: 'select',
      label: 'Plan variant',
      required: true,
      defaultValue: 'core',
      options: [
        { label: 'Core', value: 'core' },
        { label: 'Advanced', value: 'advanced' },
      ],
    },
    {
      name: 'planName',
      type: 'text',
      label: 'Plan name',
      localized: true,
      required: true,
      admin: { placeholder: 'Core' },
    },
    {
      name: 'price',
      type: 'text',
      label: 'Price (e.g. €99)',
      localized: true,
      required: true,
    },
    {
      name: 'priceNote',
      type: 'text',
      label: 'Price note',
      localized: true,
      admin: { placeholder: '4-month minimum · billed monthly' },
    },
    {
      name: 'switchLinkText',
      type: 'text',
      label: 'Switch plan link text',
      localized: true,
      admin: { placeholder: 'Looking at Advanced instead? →' },
    },
    {
      name: 'switchLinkHref',
      type: 'text',
      label: 'Switch plan link href',
    },
    {
      name: 'bullets',
      type: 'array',
      label: 'Feature bullets',
      fields: [
        {
          name: 'text',
          type: 'text',
          label: 'Text',
          localized: true,
          required: true,
        },
      ],
    },
    {
      name: 'primaryCtaText',
      type: 'text',
      label: 'Primary CTA text',
      localized: true,
      required: true,
      admin: { placeholder: 'Start Core · 4-month' },
    },
    {
      name: 'primaryCtaPrice',
      type: 'text',
      label: 'Primary CTA price label',
      localized: true,
      admin: { placeholder: '€99/mo' },
    },
    {
      name: 'primaryCtaHref',
      type: 'text',
      label: 'Primary CTA href',
      required: true,
    },
    {
      name: 'secondaryCtaText',
      type: 'text',
      label: 'Secondary CTA text (optional)',
      localized: true,
      admin: { placeholder: 'or pay monthly at €109/mo →' },
    },
    {
      name: 'secondaryCtaHref',
      type: 'text',
      label: 'Secondary CTA href',
    },
    {
      name: 'ctaSubText',
      type: 'text',
      label: 'CTA sub text',
      localized: true,
      admin: { placeholder: 'Monthly billing · cancel anytime' },
    },
  ],
}
