import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_blocks_yp_hero_locales" ADD COLUMN "primary_button_url" varchar;
  ALTER TABLE "pages_blocks_yp_buy_box_options_locales" ADD COLUMN "cta_href" varchar DEFAULT '#';
  ALTER TABLE "pages_blocks_order_step_nav_locales" ADD COLUMN "logo_url" varchar DEFAULT '/';
  ALTER TABLE "pages_blocks_order_step_nav_locales" ADD COLUMN "step1_url" varchar;
  ALTER TABLE "pages_blocks_order_step_nav_locales" ADD COLUMN "step2_url" varchar;
  ALTER TABLE "pages_blocks_order_step_nav_locales" ADD COLUMN "step3_url" varchar;
  ALTER TABLE "pages_blocks_legal_strip_links_locales" ADD COLUMN "url" varchar;
  ALTER TABLE "pages_blocks_end_card_ctas_locales" ADD COLUMN "href" varchar;
  ALTER TABLE "pages_blocks_plan_summary_card_locales" ADD COLUMN "switch_link_href" varchar;
  ALTER TABLE "pages_blocks_plan_summary_card_locales" ADD COLUMN "primary_cta_href" varchar;
  ALTER TABLE "pages_blocks_plan_summary_card_locales" ADD COLUMN "secondary_cta_href" varchar;
  ALTER TABLE "pages_blocks_cycles_pricing_grid_locales" ADD COLUMN "cta_href" varchar;
  ALTER TABLE "pages_blocks_cycles_pricing_grid_locales" ADD COLUMN "cta_href2" varchar;
  ALTER TABLE "pages_blocks_reinforce_cta_locales" ADD COLUMN "cta_href" varchar;
  ALTER TABLE "pages_blocks_reinforce_cta_locales" ADD COLUMN "cta_href2" varchar;
  ALTER TABLE "pages_blocks_plan_pivot_locales" ADD COLUMN "cta_href" varchar;
  ALTER TABLE "pages_blocks_sticky_cta_bar_locales" ADD COLUMN "primary_cta_href" varchar;
  ALTER TABLE "pages_blocks_sticky_cta_bar_locales" ADD COLUMN "secondary_cta_href" varchar;
  ALTER TABLE "pages_blocks_plan_selector_plans_locales" ADD COLUMN "monthly_link_href" varchar;
  ALTER TABLE "pages_blocks_plan_sticky_bar_plans_locales" ADD COLUMN "cta_href" varchar;
  ALTER TABLE "pages_blocks_cycle_selector_locales" ADD COLUMN "switch_link_href" varchar;
  ALTER TABLE "pages_blocks_cycle_selector_locales" ADD COLUMN "monthly_checkout_href" varchar;
  ALTER TABLE "pages_blocks_close_band_locales" ADD COLUMN "cta_href" varchar;
  ALTER TABLE "_pages_v_blocks_yp_hero_locales" ADD COLUMN "primary_button_url" varchar;
  ALTER TABLE "_pages_v_blocks_yp_buy_box_options_locales" ADD COLUMN "cta_href" varchar DEFAULT '#';
  ALTER TABLE "_pages_v_blocks_order_step_nav_locales" ADD COLUMN "logo_url" varchar DEFAULT '/';
  ALTER TABLE "_pages_v_blocks_order_step_nav_locales" ADD COLUMN "step1_url" varchar;
  ALTER TABLE "_pages_v_blocks_order_step_nav_locales" ADD COLUMN "step2_url" varchar;
  ALTER TABLE "_pages_v_blocks_order_step_nav_locales" ADD COLUMN "step3_url" varchar;
  ALTER TABLE "_pages_v_blocks_legal_strip_links_locales" ADD COLUMN "url" varchar;
  ALTER TABLE "_pages_v_blocks_end_card_ctas_locales" ADD COLUMN "href" varchar;
  ALTER TABLE "_pages_v_blocks_plan_summary_card_locales" ADD COLUMN "switch_link_href" varchar;
  ALTER TABLE "_pages_v_blocks_plan_summary_card_locales" ADD COLUMN "primary_cta_href" varchar;
  ALTER TABLE "_pages_v_blocks_plan_summary_card_locales" ADD COLUMN "secondary_cta_href" varchar;
  ALTER TABLE "_pages_v_blocks_cycles_pricing_grid_locales" ADD COLUMN "cta_href" varchar;
  ALTER TABLE "_pages_v_blocks_cycles_pricing_grid_locales" ADD COLUMN "cta_href2" varchar;
  ALTER TABLE "_pages_v_blocks_reinforce_cta_locales" ADD COLUMN "cta_href" varchar;
  ALTER TABLE "_pages_v_blocks_reinforce_cta_locales" ADD COLUMN "cta_href2" varchar;
  ALTER TABLE "_pages_v_blocks_plan_pivot_locales" ADD COLUMN "cta_href" varchar;
  ALTER TABLE "_pages_v_blocks_sticky_cta_bar_locales" ADD COLUMN "primary_cta_href" varchar;
  ALTER TABLE "_pages_v_blocks_sticky_cta_bar_locales" ADD COLUMN "secondary_cta_href" varchar;
  ALTER TABLE "_pages_v_blocks_plan_selector_plans_locales" ADD COLUMN "monthly_link_href" varchar;
  ALTER TABLE "_pages_v_blocks_plan_sticky_bar_plans_locales" ADD COLUMN "cta_href" varchar;
  ALTER TABLE "_pages_v_blocks_cycle_selector_locales" ADD COLUMN "switch_link_href" varchar;
  ALTER TABLE "_pages_v_blocks_cycle_selector_locales" ADD COLUMN "monthly_checkout_href" varchar;
  ALTER TABLE "_pages_v_blocks_close_band_locales" ADD COLUMN "cta_href" varchar;
  ALTER TABLE "pages_blocks_yp_hero" DROP COLUMN "primary_button_url";
  ALTER TABLE "pages_blocks_yp_buy_box_options" DROP COLUMN "cta_href";
  ALTER TABLE "pages_blocks_order_step_nav" DROP COLUMN "logo_url";
  ALTER TABLE "pages_blocks_order_step_nav" DROP COLUMN "step1_url";
  ALTER TABLE "pages_blocks_order_step_nav" DROP COLUMN "step2_url";
  ALTER TABLE "pages_blocks_order_step_nav" DROP COLUMN "step3_url";
  ALTER TABLE "pages_blocks_legal_strip_links" DROP COLUMN "url";
  ALTER TABLE "pages_blocks_end_card_ctas" DROP COLUMN "href";
  ALTER TABLE "pages_blocks_plan_summary_card" DROP COLUMN "switch_link_href";
  ALTER TABLE "pages_blocks_plan_summary_card" DROP COLUMN "primary_cta_href";
  ALTER TABLE "pages_blocks_plan_summary_card" DROP COLUMN "secondary_cta_href";
  ALTER TABLE "pages_blocks_cycles_pricing_grid" DROP COLUMN "cta_href";
  ALTER TABLE "pages_blocks_cycles_pricing_grid" DROP COLUMN "cta_href2";
  ALTER TABLE "pages_blocks_reinforce_cta" DROP COLUMN "cta_href";
  ALTER TABLE "pages_blocks_reinforce_cta" DROP COLUMN "cta_href2";
  ALTER TABLE "pages_blocks_plan_pivot" DROP COLUMN "cta_href";
  ALTER TABLE "pages_blocks_sticky_cta_bar" DROP COLUMN "primary_cta_href";
  ALTER TABLE "pages_blocks_sticky_cta_bar" DROP COLUMN "secondary_cta_href";
  ALTER TABLE "pages_blocks_plan_selector_plans" DROP COLUMN "monthly_link_href";
  ALTER TABLE "pages_blocks_plan_sticky_bar_plans" DROP COLUMN "cta_href";
  ALTER TABLE "pages_blocks_cycle_selector" DROP COLUMN "switch_link_href";
  ALTER TABLE "pages_blocks_cycle_selector" DROP COLUMN "monthly_checkout_href";
  ALTER TABLE "pages_blocks_close_band" DROP COLUMN "cta_href";
  ALTER TABLE "_pages_v_blocks_yp_hero" DROP COLUMN "primary_button_url";
  ALTER TABLE "_pages_v_blocks_yp_buy_box_options" DROP COLUMN "cta_href";
  ALTER TABLE "_pages_v_blocks_order_step_nav" DROP COLUMN "logo_url";
  ALTER TABLE "_pages_v_blocks_order_step_nav" DROP COLUMN "step1_url";
  ALTER TABLE "_pages_v_blocks_order_step_nav" DROP COLUMN "step2_url";
  ALTER TABLE "_pages_v_blocks_order_step_nav" DROP COLUMN "step3_url";
  ALTER TABLE "_pages_v_blocks_legal_strip_links" DROP COLUMN "url";
  ALTER TABLE "_pages_v_blocks_end_card_ctas" DROP COLUMN "href";
  ALTER TABLE "_pages_v_blocks_plan_summary_card" DROP COLUMN "switch_link_href";
  ALTER TABLE "_pages_v_blocks_plan_summary_card" DROP COLUMN "primary_cta_href";
  ALTER TABLE "_pages_v_blocks_plan_summary_card" DROP COLUMN "secondary_cta_href";
  ALTER TABLE "_pages_v_blocks_cycles_pricing_grid" DROP COLUMN "cta_href";
  ALTER TABLE "_pages_v_blocks_cycles_pricing_grid" DROP COLUMN "cta_href2";
  ALTER TABLE "_pages_v_blocks_reinforce_cta" DROP COLUMN "cta_href";
  ALTER TABLE "_pages_v_blocks_reinforce_cta" DROP COLUMN "cta_href2";
  ALTER TABLE "_pages_v_blocks_plan_pivot" DROP COLUMN "cta_href";
  ALTER TABLE "_pages_v_blocks_sticky_cta_bar" DROP COLUMN "primary_cta_href";
  ALTER TABLE "_pages_v_blocks_sticky_cta_bar" DROP COLUMN "secondary_cta_href";
  ALTER TABLE "_pages_v_blocks_plan_selector_plans" DROP COLUMN "monthly_link_href";
  ALTER TABLE "_pages_v_blocks_plan_sticky_bar_plans" DROP COLUMN "cta_href";
  ALTER TABLE "_pages_v_blocks_cycle_selector" DROP COLUMN "switch_link_href";
  ALTER TABLE "_pages_v_blocks_cycle_selector" DROP COLUMN "monthly_checkout_href";
  ALTER TABLE "_pages_v_blocks_close_band" DROP COLUMN "cta_href";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_blocks_yp_hero" ADD COLUMN "primary_button_url" varchar;
  ALTER TABLE "pages_blocks_yp_buy_box_options" ADD COLUMN "cta_href" varchar DEFAULT '#';
  ALTER TABLE "pages_blocks_order_step_nav" ADD COLUMN "logo_url" varchar DEFAULT '/';
  ALTER TABLE "pages_blocks_order_step_nav" ADD COLUMN "step1_url" varchar;
  ALTER TABLE "pages_blocks_order_step_nav" ADD COLUMN "step2_url" varchar;
  ALTER TABLE "pages_blocks_order_step_nav" ADD COLUMN "step3_url" varchar;
  ALTER TABLE "pages_blocks_legal_strip_links" ADD COLUMN "url" varchar;
  ALTER TABLE "pages_blocks_end_card_ctas" ADD COLUMN "href" varchar;
  ALTER TABLE "pages_blocks_plan_summary_card" ADD COLUMN "switch_link_href" varchar;
  ALTER TABLE "pages_blocks_plan_summary_card" ADD COLUMN "primary_cta_href" varchar;
  ALTER TABLE "pages_blocks_plan_summary_card" ADD COLUMN "secondary_cta_href" varchar;
  ALTER TABLE "pages_blocks_cycles_pricing_grid" ADD COLUMN "cta_href" varchar;
  ALTER TABLE "pages_blocks_cycles_pricing_grid" ADD COLUMN "cta_href2" varchar;
  ALTER TABLE "pages_blocks_reinforce_cta" ADD COLUMN "cta_href" varchar;
  ALTER TABLE "pages_blocks_reinforce_cta" ADD COLUMN "cta_href2" varchar;
  ALTER TABLE "pages_blocks_plan_pivot" ADD COLUMN "cta_href" varchar;
  ALTER TABLE "pages_blocks_sticky_cta_bar" ADD COLUMN "primary_cta_href" varchar;
  ALTER TABLE "pages_blocks_sticky_cta_bar" ADD COLUMN "secondary_cta_href" varchar;
  ALTER TABLE "pages_blocks_plan_selector_plans" ADD COLUMN "monthly_link_href" varchar;
  ALTER TABLE "pages_blocks_plan_sticky_bar_plans" ADD COLUMN "cta_href" varchar;
  ALTER TABLE "pages_blocks_cycle_selector" ADD COLUMN "switch_link_href" varchar;
  ALTER TABLE "pages_blocks_cycle_selector" ADD COLUMN "monthly_checkout_href" varchar;
  ALTER TABLE "pages_blocks_close_band" ADD COLUMN "cta_href" varchar;
  ALTER TABLE "_pages_v_blocks_yp_hero" ADD COLUMN "primary_button_url" varchar;
  ALTER TABLE "_pages_v_blocks_yp_buy_box_options" ADD COLUMN "cta_href" varchar DEFAULT '#';
  ALTER TABLE "_pages_v_blocks_order_step_nav" ADD COLUMN "logo_url" varchar DEFAULT '/';
  ALTER TABLE "_pages_v_blocks_order_step_nav" ADD COLUMN "step1_url" varchar;
  ALTER TABLE "_pages_v_blocks_order_step_nav" ADD COLUMN "step2_url" varchar;
  ALTER TABLE "_pages_v_blocks_order_step_nav" ADD COLUMN "step3_url" varchar;
  ALTER TABLE "_pages_v_blocks_legal_strip_links" ADD COLUMN "url" varchar;
  ALTER TABLE "_pages_v_blocks_end_card_ctas" ADD COLUMN "href" varchar;
  ALTER TABLE "_pages_v_blocks_plan_summary_card" ADD COLUMN "switch_link_href" varchar;
  ALTER TABLE "_pages_v_blocks_plan_summary_card" ADD COLUMN "primary_cta_href" varchar;
  ALTER TABLE "_pages_v_blocks_plan_summary_card" ADD COLUMN "secondary_cta_href" varchar;
  ALTER TABLE "_pages_v_blocks_cycles_pricing_grid" ADD COLUMN "cta_href" varchar;
  ALTER TABLE "_pages_v_blocks_cycles_pricing_grid" ADD COLUMN "cta_href2" varchar;
  ALTER TABLE "_pages_v_blocks_reinforce_cta" ADD COLUMN "cta_href" varchar;
  ALTER TABLE "_pages_v_blocks_reinforce_cta" ADD COLUMN "cta_href2" varchar;
  ALTER TABLE "_pages_v_blocks_plan_pivot" ADD COLUMN "cta_href" varchar;
  ALTER TABLE "_pages_v_blocks_sticky_cta_bar" ADD COLUMN "primary_cta_href" varchar;
  ALTER TABLE "_pages_v_blocks_sticky_cta_bar" ADD COLUMN "secondary_cta_href" varchar;
  ALTER TABLE "_pages_v_blocks_plan_selector_plans" ADD COLUMN "monthly_link_href" varchar;
  ALTER TABLE "_pages_v_blocks_plan_sticky_bar_plans" ADD COLUMN "cta_href" varchar;
  ALTER TABLE "_pages_v_blocks_cycle_selector" ADD COLUMN "switch_link_href" varchar;
  ALTER TABLE "_pages_v_blocks_cycle_selector" ADD COLUMN "monthly_checkout_href" varchar;
  ALTER TABLE "_pages_v_blocks_close_band" ADD COLUMN "cta_href" varchar;
  ALTER TABLE "pages_blocks_yp_hero_locales" DROP COLUMN "primary_button_url";
  ALTER TABLE "pages_blocks_yp_buy_box_options_locales" DROP COLUMN "cta_href";
  ALTER TABLE "pages_blocks_order_step_nav_locales" DROP COLUMN "logo_url";
  ALTER TABLE "pages_blocks_order_step_nav_locales" DROP COLUMN "step1_url";
  ALTER TABLE "pages_blocks_order_step_nav_locales" DROP COLUMN "step2_url";
  ALTER TABLE "pages_blocks_order_step_nav_locales" DROP COLUMN "step3_url";
  ALTER TABLE "pages_blocks_legal_strip_links_locales" DROP COLUMN "url";
  ALTER TABLE "pages_blocks_end_card_ctas_locales" DROP COLUMN "href";
  ALTER TABLE "pages_blocks_plan_summary_card_locales" DROP COLUMN "switch_link_href";
  ALTER TABLE "pages_blocks_plan_summary_card_locales" DROP COLUMN "primary_cta_href";
  ALTER TABLE "pages_blocks_plan_summary_card_locales" DROP COLUMN "secondary_cta_href";
  ALTER TABLE "pages_blocks_cycles_pricing_grid_locales" DROP COLUMN "cta_href";
  ALTER TABLE "pages_blocks_cycles_pricing_grid_locales" DROP COLUMN "cta_href2";
  ALTER TABLE "pages_blocks_reinforce_cta_locales" DROP COLUMN "cta_href";
  ALTER TABLE "pages_blocks_reinforce_cta_locales" DROP COLUMN "cta_href2";
  ALTER TABLE "pages_blocks_plan_pivot_locales" DROP COLUMN "cta_href";
  ALTER TABLE "pages_blocks_sticky_cta_bar_locales" DROP COLUMN "primary_cta_href";
  ALTER TABLE "pages_blocks_sticky_cta_bar_locales" DROP COLUMN "secondary_cta_href";
  ALTER TABLE "pages_blocks_plan_selector_plans_locales" DROP COLUMN "monthly_link_href";
  ALTER TABLE "pages_blocks_plan_sticky_bar_plans_locales" DROP COLUMN "cta_href";
  ALTER TABLE "pages_blocks_cycle_selector_locales" DROP COLUMN "switch_link_href";
  ALTER TABLE "pages_blocks_cycle_selector_locales" DROP COLUMN "monthly_checkout_href";
  ALTER TABLE "pages_blocks_close_band_locales" DROP COLUMN "cta_href";
  ALTER TABLE "_pages_v_blocks_yp_hero_locales" DROP COLUMN "primary_button_url";
  ALTER TABLE "_pages_v_blocks_yp_buy_box_options_locales" DROP COLUMN "cta_href";
  ALTER TABLE "_pages_v_blocks_order_step_nav_locales" DROP COLUMN "logo_url";
  ALTER TABLE "_pages_v_blocks_order_step_nav_locales" DROP COLUMN "step1_url";
  ALTER TABLE "_pages_v_blocks_order_step_nav_locales" DROP COLUMN "step2_url";
  ALTER TABLE "_pages_v_blocks_order_step_nav_locales" DROP COLUMN "step3_url";
  ALTER TABLE "_pages_v_blocks_legal_strip_links_locales" DROP COLUMN "url";
  ALTER TABLE "_pages_v_blocks_end_card_ctas_locales" DROP COLUMN "href";
  ALTER TABLE "_pages_v_blocks_plan_summary_card_locales" DROP COLUMN "switch_link_href";
  ALTER TABLE "_pages_v_blocks_plan_summary_card_locales" DROP COLUMN "primary_cta_href";
  ALTER TABLE "_pages_v_blocks_plan_summary_card_locales" DROP COLUMN "secondary_cta_href";
  ALTER TABLE "_pages_v_blocks_cycles_pricing_grid_locales" DROP COLUMN "cta_href";
  ALTER TABLE "_pages_v_blocks_cycles_pricing_grid_locales" DROP COLUMN "cta_href2";
  ALTER TABLE "_pages_v_blocks_reinforce_cta_locales" DROP COLUMN "cta_href";
  ALTER TABLE "_pages_v_blocks_reinforce_cta_locales" DROP COLUMN "cta_href2";
  ALTER TABLE "_pages_v_blocks_plan_pivot_locales" DROP COLUMN "cta_href";
  ALTER TABLE "_pages_v_blocks_sticky_cta_bar_locales" DROP COLUMN "primary_cta_href";
  ALTER TABLE "_pages_v_blocks_sticky_cta_bar_locales" DROP COLUMN "secondary_cta_href";
  ALTER TABLE "_pages_v_blocks_plan_selector_plans_locales" DROP COLUMN "monthly_link_href";
  ALTER TABLE "_pages_v_blocks_plan_sticky_bar_plans_locales" DROP COLUMN "cta_href";
  ALTER TABLE "_pages_v_blocks_cycle_selector_locales" DROP COLUMN "switch_link_href";
  ALTER TABLE "_pages_v_blocks_cycle_selector_locales" DROP COLUMN "monthly_checkout_href";
  ALTER TABLE "_pages_v_blocks_close_band_locales" DROP COLUMN "cta_href";`)
}
