import { MigrateUpArgs, MigrateDownArgs } from '@payloadcms/db-postgres'
import { sql } from 'drizzle-orm'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  // Check that the headers table exists before trying to seed it.
  // This migration must run AFTER the DDL migration generated by `migrate:create`.
  const result = await db.execute(sql`
    SELECT EXISTS (
      SELECT FROM information_schema.tables
      WHERE table_schema = 'public' AND table_name = 'headers'
    ) AS exists
  `)

  const headersTableExists = result.rows[0]?.exists === true

  if (!headersTableExists) {
    payload.logger.warn(
      'headers/footers tables do not exist yet — skipping seed. ' +
      'Run `npx payload migrate:create` to generate the schema migration, then re-run migrate.',
    )
    return
  }

  const existingHeaders = await payload.find({
    collection: 'headers',
    limit: 1,
    overrideAccess: true,
    req,
  })

  if (existingHeaders.totalDocs === 0) {
    await payload.create({
      collection: 'headers',
      data: {
        name: 'Default',
        isDefault: true,
        theme: 'light',
      } as any,
      overrideAccess: true,
      req,
    })
    payload.logger.info('Created default header document.')
  }

  const footersTableExists = await db.execute(sql`
    SELECT EXISTS (
      SELECT FROM information_schema.tables
      WHERE table_schema = 'public' AND table_name = 'footers'
    ) AS exists
  `)

  if (footersTableExists.rows[0]?.exists !== true) return

  const existingFooters = await payload.find({
    collection: 'footers',
    limit: 1,
    overrideAccess: true,
    req,
  })

  if (existingFooters.totalDocs === 0) {
    await payload.create({
      collection: 'footers',
      data: {
        name: 'Default',
        isDefault: true,
        theme: 'light',
      } as any,
      overrideAccess: true,
      req,
    })
    payload.logger.info('Created default footer document.')
  }
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  // No destructive rollback.
}
