import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

// Forward-only cleanup: drops the 19 unused page block types that were removed
// from the Pages collection (each confirmed 0 rows on STG + PROD). It only
// touches pages_blocks_* / _pages_v_blocks_* tables and their block-specific
// enums — nothing else.
//
// NOTE: `payload migrate:create` also bundled in unrelated changes (an `nl`
// locale ADD VALUE, a `categories` relation drop, and a ~880-statement locale
// re-cast in down()) because its snapshot baseline lags behind the colleagues'
// already-applied migrations. Those were stripped here on purpose — running them
// would clash with the live STG/PROD state (e.g. `nl` already exists). down() is
// intentionally a no-op: the dropped tables were empty, so there is nothing to
// restore, and the generated reverse would re-run the dangerous locale re-cast.
export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
  ALTER TABLE "pages_blocks_cta_links" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_cta_links_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_cta" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_media_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_archive" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_form_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_welcome_banner_banner_labels" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_welcome_banner_banner_labels_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_welcome_banner" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_welcome_banner_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_details_banner_content" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_details_banner_content_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_details_banner" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_details_banner_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_mission_banner_images" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_mission_banner" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_mission_banner_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_form_custom" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_form_custom_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_key_takeaways_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_key_takeaways_items_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_key_takeaways" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_faq_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_faq_items_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_faq" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_data_table_column_headers" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_data_table_column_headers_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_data_table_rows_cells" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_data_table_rows_cells_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_data_table_rows" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_data_table" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_data_table_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_cta_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_cta_block_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_bullet_list_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_bullet_list_items_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_bullet_list" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_bullet_list_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_contact_form" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_contact_form_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_contact_info_social_links" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_contact_info" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_contact_info_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_contact_section_info_social_links" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_contact_section" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_contact_section_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_product_showcase_panel_thumbnails" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_product_showcase_panel_thumbnails_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_product_showcase_plans_features" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_product_showcase_plans_features_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_product_showcase_plans_prices" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_product_showcase_plans_prices_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_product_showcase_plans" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_product_showcase_plans_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_product_showcase_faq_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_product_showcase_faq_items_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_product_showcase" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_product_showcase_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_early_access_variants" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_early_access_variants_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_early_access" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_early_access_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_trust_seals_bar_seals" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_trust_seals_bar_seals_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_trust_seals_bar" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_cta_links" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_cta_links_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_cta" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_media_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_archive" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_form_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_welcome_banner_banner_labels" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_welcome_banner_banner_labels_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_welcome_banner" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_welcome_banner_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_details_banner_content" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_details_banner_content_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_details_banner" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_details_banner_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_mission_banner_images" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_mission_banner" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_mission_banner_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_form_custom" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_form_custom_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_key_takeaways_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_key_takeaways_items_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_key_takeaways" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_faq_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_faq_items_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_faq" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_data_table_column_headers" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_data_table_column_headers_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_data_table_rows_cells" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_data_table_rows_cells_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_data_table_rows" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_data_table" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_data_table_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_cta_block" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_cta_block_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_bullet_list_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_bullet_list_items_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_bullet_list" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_bullet_list_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_contact_form" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_contact_form_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_contact_info_social_links" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_contact_info" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_contact_info_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_contact_section_info_social_links" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_contact_section" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_contact_section_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_product_showcase_panel_thumbnails" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_product_showcase_panel_thumbnails_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_product_showcase_plans_features" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_product_showcase_plans_features_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_product_showcase_plans_prices" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_product_showcase_plans_prices_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_product_showcase_plans" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_product_showcase_plans_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_product_showcase_faq_items" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_product_showcase_faq_items_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_product_showcase" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_product_showcase_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_early_access_variants" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_early_access_variants_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_early_access" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_early_access_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_trust_seals_bar_seals" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_trust_seals_bar_seals_locales" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_trust_seals_bar" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "pages_blocks_cta_links" CASCADE;
  DROP TABLE "pages_blocks_cta_links_locales" CASCADE;
  DROP TABLE "pages_blocks_cta" CASCADE;
  DROP TABLE "pages_blocks_media_block" CASCADE;
  DROP TABLE "pages_blocks_archive" CASCADE;
  DROP TABLE "pages_blocks_form_block" CASCADE;
  DROP TABLE "pages_blocks_welcome_banner_banner_labels" CASCADE;
  DROP TABLE "pages_blocks_welcome_banner_banner_labels_locales" CASCADE;
  DROP TABLE "pages_blocks_welcome_banner" CASCADE;
  DROP TABLE "pages_blocks_welcome_banner_locales" CASCADE;
  DROP TABLE "pages_blocks_details_banner_content" CASCADE;
  DROP TABLE "pages_blocks_details_banner_content_locales" CASCADE;
  DROP TABLE "pages_blocks_details_banner" CASCADE;
  DROP TABLE "pages_blocks_details_banner_locales" CASCADE;
  DROP TABLE "pages_blocks_mission_banner_images" CASCADE;
  DROP TABLE "pages_blocks_mission_banner" CASCADE;
  DROP TABLE "pages_blocks_mission_banner_locales" CASCADE;
  DROP TABLE "pages_blocks_form_custom" CASCADE;
  DROP TABLE "pages_blocks_form_custom_locales" CASCADE;
  DROP TABLE "pages_blocks_key_takeaways_items" CASCADE;
  DROP TABLE "pages_blocks_key_takeaways_items_locales" CASCADE;
  DROP TABLE "pages_blocks_key_takeaways" CASCADE;
  DROP TABLE "pages_blocks_faq_items" CASCADE;
  DROP TABLE "pages_blocks_faq_items_locales" CASCADE;
  DROP TABLE "pages_blocks_faq" CASCADE;
  DROP TABLE "pages_blocks_data_table_column_headers" CASCADE;
  DROP TABLE "pages_blocks_data_table_column_headers_locales" CASCADE;
  DROP TABLE "pages_blocks_data_table_rows_cells" CASCADE;
  DROP TABLE "pages_blocks_data_table_rows_cells_locales" CASCADE;
  DROP TABLE "pages_blocks_data_table_rows" CASCADE;
  DROP TABLE "pages_blocks_data_table" CASCADE;
  DROP TABLE "pages_blocks_data_table_locales" CASCADE;
  DROP TABLE "pages_blocks_cta_block" CASCADE;
  DROP TABLE "pages_blocks_cta_block_locales" CASCADE;
  DROP TABLE "pages_blocks_bullet_list_items" CASCADE;
  DROP TABLE "pages_blocks_bullet_list_items_locales" CASCADE;
  DROP TABLE "pages_blocks_bullet_list" CASCADE;
  DROP TABLE "pages_blocks_bullet_list_locales" CASCADE;
  DROP TABLE "pages_blocks_contact_form" CASCADE;
  DROP TABLE "pages_blocks_contact_form_locales" CASCADE;
  DROP TABLE "pages_blocks_contact_info_social_links" CASCADE;
  DROP TABLE "pages_blocks_contact_info" CASCADE;
  DROP TABLE "pages_blocks_contact_info_locales" CASCADE;
  DROP TABLE "pages_blocks_contact_section_info_social_links" CASCADE;
  DROP TABLE "pages_blocks_contact_section" CASCADE;
  DROP TABLE "pages_blocks_contact_section_locales" CASCADE;
  DROP TABLE "pages_blocks_product_showcase_panel_thumbnails" CASCADE;
  DROP TABLE "pages_blocks_product_showcase_panel_thumbnails_locales" CASCADE;
  DROP TABLE "pages_blocks_product_showcase_plans_features" CASCADE;
  DROP TABLE "pages_blocks_product_showcase_plans_features_locales" CASCADE;
  DROP TABLE "pages_blocks_product_showcase_plans_prices" CASCADE;
  DROP TABLE "pages_blocks_product_showcase_plans_prices_locales" CASCADE;
  DROP TABLE "pages_blocks_product_showcase_plans" CASCADE;
  DROP TABLE "pages_blocks_product_showcase_plans_locales" CASCADE;
  DROP TABLE "pages_blocks_product_showcase_faq_items" CASCADE;
  DROP TABLE "pages_blocks_product_showcase_faq_items_locales" CASCADE;
  DROP TABLE "pages_blocks_product_showcase" CASCADE;
  DROP TABLE "pages_blocks_product_showcase_locales" CASCADE;
  DROP TABLE "pages_blocks_early_access_variants" CASCADE;
  DROP TABLE "pages_blocks_early_access_variants_locales" CASCADE;
  DROP TABLE "pages_blocks_early_access" CASCADE;
  DROP TABLE "pages_blocks_early_access_locales" CASCADE;
  DROP TABLE "pages_blocks_trust_seals_bar_seals" CASCADE;
  DROP TABLE "pages_blocks_trust_seals_bar_seals_locales" CASCADE;
  DROP TABLE "pages_blocks_trust_seals_bar" CASCADE;
  DROP TABLE "_pages_v_blocks_cta_links" CASCADE;
  DROP TABLE "_pages_v_blocks_cta_links_locales" CASCADE;
  DROP TABLE "_pages_v_blocks_cta" CASCADE;
  DROP TABLE "_pages_v_blocks_media_block" CASCADE;
  DROP TABLE "_pages_v_blocks_archive" CASCADE;
  DROP TABLE "_pages_v_blocks_form_block" CASCADE;
  DROP TABLE "_pages_v_blocks_welcome_banner_banner_labels" CASCADE;
  DROP TABLE "_pages_v_blocks_welcome_banner_banner_labels_locales" CASCADE;
  DROP TABLE "_pages_v_blocks_welcome_banner" CASCADE;
  DROP TABLE "_pages_v_blocks_welcome_banner_locales" CASCADE;
  DROP TABLE "_pages_v_blocks_details_banner_content" CASCADE;
  DROP TABLE "_pages_v_blocks_details_banner_content_locales" CASCADE;
  DROP TABLE "_pages_v_blocks_details_banner" CASCADE;
  DROP TABLE "_pages_v_blocks_details_banner_locales" CASCADE;
  DROP TABLE "_pages_v_blocks_mission_banner_images" CASCADE;
  DROP TABLE "_pages_v_blocks_mission_banner" CASCADE;
  DROP TABLE "_pages_v_blocks_mission_banner_locales" CASCADE;
  DROP TABLE "_pages_v_blocks_form_custom" CASCADE;
  DROP TABLE "_pages_v_blocks_form_custom_locales" CASCADE;
  DROP TABLE "_pages_v_blocks_key_takeaways_items" CASCADE;
  DROP TABLE "_pages_v_blocks_key_takeaways_items_locales" CASCADE;
  DROP TABLE "_pages_v_blocks_key_takeaways" CASCADE;
  DROP TABLE "_pages_v_blocks_faq_items" CASCADE;
  DROP TABLE "_pages_v_blocks_faq_items_locales" CASCADE;
  DROP TABLE "_pages_v_blocks_faq" CASCADE;
  DROP TABLE "_pages_v_blocks_data_table_column_headers" CASCADE;
  DROP TABLE "_pages_v_blocks_data_table_column_headers_locales" CASCADE;
  DROP TABLE "_pages_v_blocks_data_table_rows_cells" CASCADE;
  DROP TABLE "_pages_v_blocks_data_table_rows_cells_locales" CASCADE;
  DROP TABLE "_pages_v_blocks_data_table_rows" CASCADE;
  DROP TABLE "_pages_v_blocks_data_table" CASCADE;
  DROP TABLE "_pages_v_blocks_data_table_locales" CASCADE;
  DROP TABLE "_pages_v_blocks_cta_block" CASCADE;
  DROP TABLE "_pages_v_blocks_cta_block_locales" CASCADE;
  DROP TABLE "_pages_v_blocks_bullet_list_items" CASCADE;
  DROP TABLE "_pages_v_blocks_bullet_list_items_locales" CASCADE;
  DROP TABLE "_pages_v_blocks_bullet_list" CASCADE;
  DROP TABLE "_pages_v_blocks_bullet_list_locales" CASCADE;
  DROP TABLE "_pages_v_blocks_contact_form" CASCADE;
  DROP TABLE "_pages_v_blocks_contact_form_locales" CASCADE;
  DROP TABLE "_pages_v_blocks_contact_info_social_links" CASCADE;
  DROP TABLE "_pages_v_blocks_contact_info" CASCADE;
  DROP TABLE "_pages_v_blocks_contact_info_locales" CASCADE;
  DROP TABLE "_pages_v_blocks_contact_section_info_social_links" CASCADE;
  DROP TABLE "_pages_v_blocks_contact_section" CASCADE;
  DROP TABLE "_pages_v_blocks_contact_section_locales" CASCADE;
  DROP TABLE "_pages_v_blocks_product_showcase_panel_thumbnails" CASCADE;
  DROP TABLE "_pages_v_blocks_product_showcase_panel_thumbnails_locales" CASCADE;
  DROP TABLE "_pages_v_blocks_product_showcase_plans_features" CASCADE;
  DROP TABLE "_pages_v_blocks_product_showcase_plans_features_locales" CASCADE;
  DROP TABLE "_pages_v_blocks_product_showcase_plans_prices" CASCADE;
  DROP TABLE "_pages_v_blocks_product_showcase_plans_prices_locales" CASCADE;
  DROP TABLE "_pages_v_blocks_product_showcase_plans" CASCADE;
  DROP TABLE "_pages_v_blocks_product_showcase_plans_locales" CASCADE;
  DROP TABLE "_pages_v_blocks_product_showcase_faq_items" CASCADE;
  DROP TABLE "_pages_v_blocks_product_showcase_faq_items_locales" CASCADE;
  DROP TABLE "_pages_v_blocks_product_showcase" CASCADE;
  DROP TABLE "_pages_v_blocks_product_showcase_locales" CASCADE;
  DROP TABLE "_pages_v_blocks_early_access_variants" CASCADE;
  DROP TABLE "_pages_v_blocks_early_access_variants_locales" CASCADE;
  DROP TABLE "_pages_v_blocks_early_access" CASCADE;
  DROP TABLE "_pages_v_blocks_early_access_locales" CASCADE;
  DROP TABLE "_pages_v_blocks_trust_seals_bar_seals" CASCADE;
  DROP TABLE "_pages_v_blocks_trust_seals_bar_seals_locales" CASCADE;
  DROP TABLE "_pages_v_blocks_trust_seals_bar" CASCADE;
  DROP TYPE "public"."enum_pages_blocks_cta_links_link_type";
  DROP TYPE "public"."enum_pages_blocks_cta_links_link_appearance";
  DROP TYPE "public"."enum_pages_blocks_archive_populate_by";
  DROP TYPE "public"."enum_pages_blocks_archive_relation_to";
  DROP TYPE "public"."enum_pages_blocks_data_table_variant";
  DROP TYPE "public"."enum_pages_blocks_trust_seals_bar_seals_type";
  DROP TYPE "public"."enum__pages_v_blocks_cta_links_link_type";
  DROP TYPE "public"."enum__pages_v_blocks_cta_links_link_appearance";
  DROP TYPE "public"."enum__pages_v_blocks_archive_populate_by";
  DROP TYPE "public"."enum__pages_v_blocks_archive_relation_to";
  DROP TYPE "public"."enum__pages_v_blocks_data_table_variant";
  DROP TYPE "public"."enum__pages_v_blocks_trust_seals_bar_seals_type";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  // Intentionally a no-op. This migration only drops empty, orphaned block
  // tables that are no longer in the Pages config, so there is nothing to
  // restore. (The auto-generated reverse re-ran a full locale re-cast that would
  // break the live STG/PROD schema, so it was deliberately omitted.)
}
