/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    products: Product;
    authors: Author;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'de' | 'fr') | ('en' | 'de' | 'fr')[];
  globals: {
    header: Header;
    footer: Footer;
    navigation: Navigation;
    'site-settings': SiteSetting;
    faq: Faq;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
  };
  locale: 'en' | 'de' | 'fr';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Optional translated label. If empty, the default label will be used.
             */
            localizedLabel?: string | null;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | FormBlock
    | WelcomeBannerBlock
    | DetailsBannerBlock
    | MissionBannerBlock
    | FormCustomBlock
    | BoxCardBlock
    | FormulaCardBlock
    | ResultsCardBlock
    | ReviewCardBlock
    | StepsCardBlock
    | SymptomsCardBlock
    | VideoCardBlock
    | KeyTakeawaysBlock
    | FAQBlock
    | DataTableBlock
    | CtaBlock
    | BulletListBlock
    | ContactFormBlock
    | ContactInfoBlock
    | ContactSectionBlock
    | BenefitsBannerBlock
    | StepsBannerBlock
    | ProductBannerBlock
    | AccessBannerBlock
    | ProductShowcaseBlock
    | EarlyAccessBlock
    | EvolutionBandBlock
  )[];
  meta?: {
    /**
     * Custom meta title per page. If empty, uses page Title.
     */
    title?: string | null;
    /**
     * Custom meta description per page. If empty, uses a fallback.
     */
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * Controls indexing & link following.
     */
    robots?: ('index,follow' | 'noindex,follow' | 'index,nofollow' | 'noindex,nofollow') | null;
    /**
     * Optional override. Leave empty to use computed canonical.
     */
    canonicalURL?: string | null;
    /**
     * Optional. Defaults to Title Tag if empty.
     */
    ogTitle?: string | null;
    /**
     * Optional. Defaults to Meta Description if empty.
     */
    ogDescription?: string | null;
    /**
     * Optional. Defaults to Meta Image if empty.
     */
    ogImage?: (number | null) | Media;
  };
  publishedAt?: string | null;
  /**
   * Auto-formatted: lowercase + hyphens only. Max 70 characters.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * Max 70 characters (recommended for SEO)
   */
  title: string;
  subtitle?: string | null;
  heroImage?: (number | null) | Media;
  /**
   * Write 2–3 introductory paragraphs. This appears before all content blocks.
   */
  intro: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  schemaMarkup: {
    type: 'Article' | 'TechArticle' | 'FAQPage';
    /**
     * Optional. If empty, the post title will be used.
     */
    headline?: string | null;
    faqItems?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  relatedArticles?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta: {
    /**
     * SEO title tag. Max 60 characters. " | NB1" is added automatically.
     */
    title: string;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    /**
     * SEO meta description. Max 155 characters.
     */
    description: string;
  };
  /**
   * Primary SEO keyword for this article. For editor reference only; not rendered on the frontend.
   */
  focusKeyword?: string | null;
  publishedAt?: string | null;
  authors?: (number | Author)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
        slug?: string | null;
        credentials?: string | null;
        avatarUrl?: string | null;
      }[]
    | null;
  /**
   * Auto-formatted: lowercase + hyphens only. Max 70 characters.
   */
  slug: string;
  /**
   * How this article was created.
   */
  source?: ('manual' | 'api') | null;
  /**
   * Raw HTML from the content pipeline. Parsed automatically on save.
   */
  htmlContent?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and SEO (not decorative text).
   */
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * Used for /authors/[slug]
   */
  slug: string;
  /**
   * Example: MD, PhD, Registered Dietitian
   */
  credentials?: string | null;
  bio?: string | null;
  avatar?: (number | null) | Media;
  /**
   * Public profile URL (optional)
   */
  website?: string | null;
  /**
   * Example: Scientific Writer / Medical Reviewer
   */
  roleTitle?: string | null;
  /**
   * Example: NB1 Health GmbH
   */
  affiliation?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Optional translated label. If empty, the default label will be used.
           */
          localizedLabel?: string | null;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Optional translated label. If empty, the default label will be used.
           */
          localizedLabel?: string | null;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WelcomeBannerBlock".
 */
export interface WelcomeBannerBlock {
  logo: number | Media;
  heading: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  description: string;
  backgroundImage: number | Media;
  backgroundImageMobile: number | Media;
  copyrightText?: string | null;
  bannerLabels?:
    | {
        textLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  lineText?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'welcome-banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DetailsBannerBlock".
 */
export interface DetailsBannerBlock {
  heading: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Exactly 4 cards (layout expects 4).
   */
  content: {
    title?: string | null;
    description?: string | null;
    backgroundImage?: (number | null) | Media;
    backgroundImageMobile?: (number | null) | Media;
    imageContent?: (number | null) | Media;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'details-banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MissionBannerBlock".
 */
export interface MissionBannerBlock {
  heading: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  logo: number | Media;
  copyright: string;
  images: {
    image: number | Media;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'mission-banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormCustomBlock".
 */
export interface FormCustomBlock {
  heading: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  description: string;
  /**
   * Select the Form Builder form to submit.
   */
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'form-custom';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BoxCardBlock".
 */
export interface BoxCardBlock {
  title?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  itemsList?:
    | {
        textLabel?: string | null;
        icon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  button?: {
    label?: string | null;
    redirect?: string | null;
  };
  note?: string | null;
  backgroundImage?: {
    web?: (number | null) | Media;
    mobile?: (number | null) | Media;
  };
  boxImage?: {
    web?: (number | null) | Media;
    mobile?: (number | null) | Media;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'box-card';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormulaCardBlock".
 */
export interface FormulaCardBlock {
  title?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  kitImage?: (number | null) | Media;
  itemsList?:
    | {
        textLabel1?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        textLabel2?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        textLabel3?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  button?: {
    buttonText?: string | null;
    buttonLink?: string | null;
  };
  note?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formula-card';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResultsCardBlock".
 */
export interface ResultsCardBlock {
  title?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  itemsList?:
    | {
        itemTitle?: string | null;
        icon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  resultsCards?:
    | {
        resultTitle?: string | null;
        resultDescription?: string | null;
        resultImage?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'results-card';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReviewCardBlock".
 */
export interface ReviewCardBlock {
  title?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  description?: string | null;
  reviews?:
    | {
        reviewTitle?: string | null;
        reviewerName?: string | null;
        reviewerCountry?: string | null;
        reviewIcon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  navigation?: {
    right?: (number | null) | Media;
    left?: (number | null) | Media;
  };
  note?: {
    noteText?: string | null;
    noteIcon?: (number | null) | Media;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'review-card';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepsCardBlock".
 */
export interface StepsCardBlock {
  title?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  steps?:
    | {
        stepTitle?: string | null;
        stepNumber?: (number | null) | Media;
        icon?: (number | null) | Media;
        stepDescription?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  note?: string | null;
  button?: {
    label?: string | null;
    redirectUrl?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'steps-card';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SymptomsCardBlock".
 */
export interface SymptomsCardBlock {
  title?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  symptoms?:
    | {
        symptom?: string | null;
        id?: string | null;
      }[]
    | null;
  moreButton?: string | null;
  description?: string | null;
  testButton?: {
    buttonText?: string | null;
    buttonLink?: string | null;
  };
  symptomsImage?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'symptoms-card';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoCardBlock".
 */
export interface VideoCardBlock {
  title?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  description?: string | null;
  reviews?:
    | {
        name?: string | null;
        description?: string | null;
        review?: string | null;
        video?: (number | null) | Media;
        thumbnail?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  navigation?: {
    right?: (number | null) | Media;
    left?: (number | null) | Media;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'video-card';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "KeyTakeawaysBlock".
 */
export interface KeyTakeawaysBlock {
  items: {
    /**
     * Bold lead-in phrase, e.g. "Your microbiome filters everything you swallow."
     */
    leadIn: string;
    /**
     * Normal-weight explanation text, ideally 1–2 sentences.
     */
    explanation: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'keyTakeaways';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock".
 */
export interface FAQBlock {
  items: {
    question: string;
    answer: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DataTableBlock".
 */
export interface DataTableBlock {
  sectionTitle?: string | null;
  variant: 'glossary' | 'comparison';
  columnHeaders?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  rows: {
    cells: {
      value: string;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  /**
   * Zero-based column index to visually emphasize. Used only for comparison tables.
   */
  highlightColumn?: number | null;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'dataTable';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock".
 */
export interface CtaBlock {
  /**
   * 1–3 sentences connecting the article topic to the NB1 kit. This is the only editable content.
   */
  body: string;
  buttonUrl: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BulletListBlock".
 */
export interface BulletListBlock {
  sectionTitle?: string | null;
  items: {
    leadIn: string;
    body: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'bulletList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlock".
 */
export interface ContactFormBlock {
  title?: string | null;
  description?: string | null;
  formTitle?: string | null;
  formDescription?: string | null;
  labels?: {
    firstName?: string | null;
    lastName?: string | null;
    email?: string | null;
    message?: string | null;
  };
  placeholders?: {
    firstName?: string | null;
    lastName?: string | null;
    email?: string | null;
    message?: string | null;
  };
  submitLabel?: string | null;
  successMessage?: string | null;
  errorMessage?: string | null;
  /**
   * Email address where form submissions will be sent.
   */
  recipientEmail?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contact-form';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactInfoBlock".
 */
export interface ContactInfoBlock {
  title?: string | null;
  description?: string | null;
  phone?: string | null;
  phoneLabel?: string | null;
  email?: string | null;
  emailLabel?: string | null;
  address?: string | null;
  addressLabel?: string | null;
  hours?: string | null;
  hoursLabel?: string | null;
  socialLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  socialsLabel?: string | null;
  backgroundImage?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contact-info';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactSectionBlock".
 */
export interface ContactSectionBlock {
  form?: {
    title?: string | null;
    description?: string | null;
    formTitle?: string | null;
    formDescription?: string | null;
    labels?: {
      firstName?: string | null;
      lastName?: string | null;
      email?: string | null;
      message?: string | null;
    };
    placeholders?: {
      firstName?: string | null;
      lastName?: string | null;
      email?: string | null;
      message?: string | null;
    };
    submitLabel?: string | null;
    successMessage?: string | null;
    errorMessage?: string | null;
    /**
     * Email address where form submissions will be sent.
     */
    recipientEmail?: string | null;
  };
  info?: {
    title?: string | null;
    description?: string | null;
    phone?: string | null;
    phoneLabel?: string | null;
    email?: string | null;
    emailLabel?: string | null;
    address?: string | null;
    addressLabel?: string | null;
    hours?: string | null;
    hoursLabel?: string | null;
    socialLinks?:
      | {
          platform: string;
          url: string;
          id?: string | null;
        }[]
      | null;
    socialsLabel?: string | null;
    backgroundImage?: (number | null) | Media;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'contact-section';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BenefitsBannerBlock".
 */
export interface BenefitsBannerBlock {
  items: {
    title: string;
    icon: number | Media;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'benefitsBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepsBannerBlock".
 */
export interface StepsBannerBlock {
  title: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  subtitle?: string | null;
  /**
   * Single shared arrow used between all steps. On mobile it will be rotated 90 degrees.
   */
  arrowIcon?: (number | null) | Media;
  steps: {
    label: string;
    icon: number | Media;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'stepsBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductBannerBlock".
 */
export interface ProductBannerBlock {
  title: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  subtitle?: string | null;
  formText?: string | null;
  /**
   * Optional override for the submit button label. If empty, the selected form submit label will be used.
   */
  buttonText?: string | null;
  /**
   * Select the Form Builder form to submit.
   */
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  carouselText?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  bannerImage?: (number | null) | Media;
  bannerBackground?: (number | null) | Media;
  mobileBannerBackground?: (number | null) | Media;
  /**
   * Optional logo displayed above the title.
   */
  logo?: (number | null) | Media;
  loginButton?: {
    show?: boolean | null;
    label?: string | null;
    url?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'productBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccessBannerBlock".
 */
export interface AccessBannerBlock {
  title: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  subtitle?: string | null;
  quote?: string | null;
  formText?: string | null;
  /**
   * Optional override for the submit button label. If empty, the selected form submit label will be used.
   */
  buttonText?: string | null;
  /**
   * Select the Form Builder form to submit.
   */
  form: number | Form;
  id?: string | null;
  blockName?: string | null;
  blockType: 'accessBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductShowcaseBlock".
 */
export interface ProductShowcaseBlock {
  title: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  badge?: string | null;
  panel?: {
    thumbnails?:
      | {
          image: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Each card represents a plan (e.g. Core, Complete).
   */
  plans?:
    | {
        badgeLabel?: string | null;
        badgeHighlighted?: boolean | null;
        cardTitle: string;
        features?:
          | {
              text: string;
              highlighted?: boolean | null;
              id?: string | null;
            }[]
          | null;
        prices?:
          | {
              durationLabel: string;
              priceLabel: string;
              perDayLabel?: string | null;
              isDefault?: boolean | null;
              id?: string | null;
            }[]
          | null;
        buttonLabel?: string | null;
        buttonLink?: string | null;
        id?: string | null;
      }[]
    | null;
  faqItems?:
    | {
        question: string;
        answer?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'productShowcase';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EarlyAccessBlock".
 */
export interface EarlyAccessBlock {
  /**
   * Main heading shown by default.
   */
  title: string;
  /**
   * Supporting text below the title.
   */
  subtitle?: string | null;
  /**
   * Small eyebrow label displayed above the title.
   */
  headline?: string | null;
  /**
   * Optional. Overrides the submit button label from the selected form.
   */
  buttonText?: string | null;
  /**
   * Select the Form Builder form to render.
   */
  form: number | Form;
  /**
   * Each entry overrides content when ?variant=<key> is present in the URL. Leave override fields empty to fall back to the defaults above.
   */
  variants?:
    | {
        /**
         * URL param value matched against ?variant=. Example: "existence"
         */
        variantKey: string;
        /**
         * Replaces the default title for this variant.
         */
        title?: string | null;
        /**
         * Replaces the default subtitle for this variant.
         */
        subtitle?: string | null;
        /**
         * Replaces the default headline for this variant.
         */
        headline?: string | null;
        /**
         * Replaces the default button text for this variant.
         */
        buttonText?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'earlyAccess';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EvolutionBandBlock".
 */
export interface EvolutionBandBlock {
  /**
   * Small label above the heading. E.g. "Your formula evolves".
   */
  eyebrow?: string | null;
  /**
   * Main heading. Use teal color for italic highlight spans.
   */
  heading?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Supporting paragraph below the heading.
   */
  subtext?: string | null;
  /**
   * Tab label. E.g. "Cycle 01".
   */
  cycle1Tag?: string | null;
  /**
   * Sub-label under the tab. E.g. "Baseline".
   */
  cycle1Version?: string | null;
  /**
   * Card title. E.g. "Your starting formula".
   */
  cycle1Name?: string | null;
  cycle1Items?:
    | {
        name?: string | null;
        /**
         * Small text next to name. E.g. "5 strains" or "EPA + DHA".
         */
        detail?: string | null;
        /**
         * Teal benefit label. E.g. "Calmer digestion".
         */
        benefit?: string | null;
        /**
         * E.g. "50B CFU".
         */
        dose?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * E.g. "3 of 6 teams flagged. Protocol targets the gaps.".
   */
  cycle1Footer?: string | null;
  /**
   * Tab label. E.g. "Cycle 02".
   */
  cycle2Tag?: string | null;
  /**
   * Sub-label under the tab. E.g. "Re-formulated".
   */
  cycle2Version?: string | null;
  /**
   * Card title. E.g. "Your formula, updated".
   */
  cycle2Name?: string | null;
  /**
   * Each group has its own eyebrow label and a set of delta rows shown inside the Cycle 2 card.
   */
  biologyGroups?:
    | {
        /**
         * E.g. "Your biology shifted".
         */
        eyebrow?: string | null;
        rows?:
          | {
              label?: string | null;
              /**
               * E.g. "+22%", "−9%", "New".
               */
              delta?: string | null;
              direction?: ('up' | 'down' | 'new') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  cycle2Items?:
    | {
        name?: string | null;
        /**
         * Reason note. E.g. "sleep markers shifted".
         */
        detail?: string | null;
        dose?: string | null;
        status?: ('unchanged' | 'up' | 'down' | 'removed' | 'added') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * E.g. "Same protocol size. Different composition. Your biology moved.".
   */
  cycle2Footer?: string | null;
  /**
   * Each entry overrides content when ?v=<key> is present in the URL. Variant 1 can be light mode, Variant 2 dark mode, etc. Leave override fields empty to fall back to the defaults above.
   */
  variants?:
    | {
        /**
         * URL param value matched against ?v=. Example: "dark"
         */
        variantKey: string;
        eyebrow?: string | null;
        heading?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        subtext?: string | null;
        cycle1Tag?: string | null;
        cycle1Version?: string | null;
        cycle1Name?: string | null;
        cycle1Footer?: string | null;
        cycle2Tag?: string | null;
        cycle2Version?: string | null;
        cycle2Name?: string | null;
        cycle2Footer?: string | null;
        /**
         * Enable dark (navy) background for this variant.
         */
        darkMode?: boolean | null;
        cycle1Items?:
          | {
              name?: string | null;
              detail?: string | null;
              benefit?: string | null;
              dose?: string | null;
              id?: string | null;
            }[]
          | null;
        biologyGroups?:
          | {
              eyebrow?: string | null;
              rows?:
                | {
                    label?: string | null;
                    delta?: string | null;
                    direction?: ('up' | 'down' | 'new') | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        cycle2Items?:
          | {
              name?: string | null;
              detail?: string | null;
              dose?: string | null;
              status?: ('unchanged' | 'up' | 'down' | 'removed' | 'added') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'evolutionBand';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  description: string;
  slug: string;
  brandName?: string | null;
  manufacturerName?: string | null;
  /**
   * Leave empty to auto-generate from localized fields.
   */
  jsonLd?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    localizedLabel?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        'welcome-banner'?: T | WelcomeBannerBlockSelect<T>;
        'details-banner'?: T | DetailsBannerBlockSelect<T>;
        'mission-banner'?: T | MissionBannerBlockSelect<T>;
        'form-custom'?: T | FormCustomBlockSelect<T>;
        'box-card'?: T | BoxCardBlockSelect<T>;
        'formula-card'?: T | FormulaCardBlockSelect<T>;
        'results-card'?: T | ResultsCardBlockSelect<T>;
        'review-card'?: T | ReviewCardBlockSelect<T>;
        'steps-card'?: T | StepsCardBlockSelect<T>;
        'symptoms-card'?: T | SymptomsCardBlockSelect<T>;
        'video-card'?: T | VideoCardBlockSelect<T>;
        keyTakeaways?: T | KeyTakeawaysBlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        dataTable?: T | DataTableBlockSelect<T>;
        ctaBlock?: T | CtaBlockSelect<T>;
        bulletList?: T | BulletListBlockSelect<T>;
        'contact-form'?: T | ContactFormBlockSelect<T>;
        'contact-info'?: T | ContactInfoBlockSelect<T>;
        'contact-section'?: T | ContactSectionBlockSelect<T>;
        benefitsBanner?: T | BenefitsBannerBlockSelect<T>;
        stepsBanner?: T | StepsBannerBlockSelect<T>;
        productBanner?: T | ProductBannerBlockSelect<T>;
        accessBanner?: T | AccessBannerBlockSelect<T>;
        productShowcase?: T | ProductShowcaseBlockSelect<T>;
        earlyAccess?: T | EarlyAccessBlockSelect<T>;
        evolutionBand?: T | EvolutionBandBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        robots?: T;
        canonicalURL?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
      };
  publishedAt?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              localizedLabel?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              localizedLabel?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WelcomeBannerBlock_select".
 */
export interface WelcomeBannerBlockSelect<T extends boolean = true> {
  logo?: T;
  heading?: T;
  description?: T;
  backgroundImage?: T;
  backgroundImageMobile?: T;
  copyrightText?: T;
  bannerLabels?:
    | T
    | {
        textLabel?: T;
        id?: T;
      };
  lineText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DetailsBannerBlock_select".
 */
export interface DetailsBannerBlockSelect<T extends boolean = true> {
  heading?: T;
  content?:
    | T
    | {
        title?: T;
        description?: T;
        backgroundImage?: T;
        backgroundImageMobile?: T;
        imageContent?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MissionBannerBlock_select".
 */
export interface MissionBannerBlockSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  logo?: T;
  copyright?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormCustomBlock_select".
 */
export interface FormCustomBlockSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BoxCardBlock_select".
 */
export interface BoxCardBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  itemsList?:
    | T
    | {
        textLabel?: T;
        icon?: T;
        id?: T;
      };
  button?:
    | T
    | {
        label?: T;
        redirect?: T;
      };
  note?: T;
  backgroundImage?:
    | T
    | {
        web?: T;
        mobile?: T;
      };
  boxImage?:
    | T
    | {
        web?: T;
        mobile?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormulaCardBlock_select".
 */
export interface FormulaCardBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  kitImage?: T;
  itemsList?:
    | T
    | {
        textLabel1?: T;
        textLabel2?: T;
        textLabel3?: T;
        id?: T;
      };
  button?:
    | T
    | {
        buttonText?: T;
        buttonLink?: T;
      };
  note?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResultsCardBlock_select".
 */
export interface ResultsCardBlockSelect<T extends boolean = true> {
  title?: T;
  itemsList?:
    | T
    | {
        itemTitle?: T;
        icon?: T;
        id?: T;
      };
  resultsCards?:
    | T
    | {
        resultTitle?: T;
        resultDescription?: T;
        resultImage?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReviewCardBlock_select".
 */
export interface ReviewCardBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  reviews?:
    | T
    | {
        reviewTitle?: T;
        reviewerName?: T;
        reviewerCountry?: T;
        reviewIcon?: T;
        id?: T;
      };
  navigation?:
    | T
    | {
        right?: T;
        left?: T;
      };
  note?:
    | T
    | {
        noteText?: T;
        noteIcon?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepsCardBlock_select".
 */
export interface StepsCardBlockSelect<T extends boolean = true> {
  title?: T;
  steps?:
    | T
    | {
        stepTitle?: T;
        stepNumber?: T;
        icon?: T;
        stepDescription?: T;
        id?: T;
      };
  note?: T;
  button?:
    | T
    | {
        label?: T;
        redirectUrl?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SymptomsCardBlock_select".
 */
export interface SymptomsCardBlockSelect<T extends boolean = true> {
  title?: T;
  symptoms?:
    | T
    | {
        symptom?: T;
        id?: T;
      };
  moreButton?: T;
  description?: T;
  testButton?:
    | T
    | {
        buttonText?: T;
        buttonLink?: T;
      };
  symptomsImage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoCardBlock_select".
 */
export interface VideoCardBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  reviews?:
    | T
    | {
        name?: T;
        description?: T;
        review?: T;
        video?: T;
        thumbnail?: T;
        id?: T;
      };
  navigation?:
    | T
    | {
        right?: T;
        left?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "KeyTakeawaysBlock_select".
 */
export interface KeyTakeawaysBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        leadIn?: T;
        explanation?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock_select".
 */
export interface FAQBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DataTableBlock_select".
 */
export interface DataTableBlockSelect<T extends boolean = true> {
  sectionTitle?: T;
  variant?: T;
  columnHeaders?:
    | T
    | {
        label?: T;
        id?: T;
      };
  rows?:
    | T
    | {
        cells?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  highlightColumn?: T;
  caption?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock_select".
 */
export interface CtaBlockSelect<T extends boolean = true> {
  body?: T;
  buttonUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BulletListBlock_select".
 */
export interface BulletListBlockSelect<T extends boolean = true> {
  sectionTitle?: T;
  items?:
    | T
    | {
        leadIn?: T;
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactFormBlock_select".
 */
export interface ContactFormBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  formTitle?: T;
  formDescription?: T;
  labels?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        email?: T;
        message?: T;
      };
  placeholders?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        email?: T;
        message?: T;
      };
  submitLabel?: T;
  successMessage?: T;
  errorMessage?: T;
  recipientEmail?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactInfoBlock_select".
 */
export interface ContactInfoBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  phone?: T;
  phoneLabel?: T;
  email?: T;
  emailLabel?: T;
  address?: T;
  addressLabel?: T;
  hours?: T;
  hoursLabel?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  socialsLabel?: T;
  backgroundImage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactSectionBlock_select".
 */
export interface ContactSectionBlockSelect<T extends boolean = true> {
  form?:
    | T
    | {
        title?: T;
        description?: T;
        formTitle?: T;
        formDescription?: T;
        labels?:
          | T
          | {
              firstName?: T;
              lastName?: T;
              email?: T;
              message?: T;
            };
        placeholders?:
          | T
          | {
              firstName?: T;
              lastName?: T;
              email?: T;
              message?: T;
            };
        submitLabel?: T;
        successMessage?: T;
        errorMessage?: T;
        recipientEmail?: T;
      };
  info?:
    | T
    | {
        title?: T;
        description?: T;
        phone?: T;
        phoneLabel?: T;
        email?: T;
        emailLabel?: T;
        address?: T;
        addressLabel?: T;
        hours?: T;
        hoursLabel?: T;
        socialLinks?:
          | T
          | {
              platform?: T;
              url?: T;
              id?: T;
            };
        socialsLabel?: T;
        backgroundImage?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BenefitsBannerBlock_select".
 */
export interface BenefitsBannerBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        title?: T;
        icon?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepsBannerBlock_select".
 */
export interface StepsBannerBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  arrowIcon?: T;
  steps?:
    | T
    | {
        label?: T;
        icon?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductBannerBlock_select".
 */
export interface ProductBannerBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  formText?: T;
  buttonText?: T;
  form?: T;
  enableIntro?: T;
  introContent?: T;
  carouselText?:
    | T
    | {
        label?: T;
        id?: T;
      };
  bannerImage?: T;
  bannerBackground?: T;
  mobileBannerBackground?: T;
  logo?: T;
  loginButton?:
    | T
    | {
        show?: T;
        label?: T;
        url?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccessBannerBlock_select".
 */
export interface AccessBannerBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  quote?: T;
  formText?: T;
  buttonText?: T;
  form?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductShowcaseBlock_select".
 */
export interface ProductShowcaseBlockSelect<T extends boolean = true> {
  title?: T;
  badge?: T;
  panel?:
    | T
    | {
        thumbnails?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  plans?:
    | T
    | {
        badgeLabel?: T;
        badgeHighlighted?: T;
        cardTitle?: T;
        features?:
          | T
          | {
              text?: T;
              highlighted?: T;
              id?: T;
            };
        prices?:
          | T
          | {
              durationLabel?: T;
              priceLabel?: T;
              perDayLabel?: T;
              isDefault?: T;
              id?: T;
            };
        buttonLabel?: T;
        buttonLink?: T;
        id?: T;
      };
  faqItems?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EarlyAccessBlock_select".
 */
export interface EarlyAccessBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  headline?: T;
  buttonText?: T;
  form?: T;
  variants?:
    | T
    | {
        variantKey?: T;
        title?: T;
        subtitle?: T;
        headline?: T;
        buttonText?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EvolutionBandBlock_select".
 */
export interface EvolutionBandBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subtext?: T;
  cycle1Tag?: T;
  cycle1Version?: T;
  cycle1Name?: T;
  cycle1Items?:
    | T
    | {
        name?: T;
        detail?: T;
        benefit?: T;
        dose?: T;
        id?: T;
      };
  cycle1Footer?: T;
  cycle2Tag?: T;
  cycle2Version?: T;
  cycle2Name?: T;
  biologyGroups?:
    | T
    | {
        eyebrow?: T;
        rows?:
          | T
          | {
              label?: T;
              delta?: T;
              direction?: T;
              id?: T;
            };
        id?: T;
      };
  cycle2Items?:
    | T
    | {
        name?: T;
        detail?: T;
        dose?: T;
        status?: T;
        id?: T;
      };
  cycle2Footer?: T;
  variants?:
    | T
    | {
        variantKey?: T;
        eyebrow?: T;
        heading?: T;
        subtext?: T;
        cycle1Tag?: T;
        cycle1Version?: T;
        cycle1Name?: T;
        cycle1Footer?: T;
        cycle2Tag?: T;
        cycle2Version?: T;
        cycle2Name?: T;
        cycle2Footer?: T;
        darkMode?: T;
        cycle1Items?:
          | T
          | {
              name?: T;
              detail?: T;
              benefit?: T;
              dose?: T;
              id?: T;
            };
        biologyGroups?:
          | T
          | {
              eyebrow?: T;
              rows?:
                | T
                | {
                    label?: T;
                    delta?: T;
                    direction?: T;
                    id?: T;
                  };
              id?: T;
            };
        cycle2Items?:
          | T
          | {
              name?: T;
              detail?: T;
              dose?: T;
              status?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  heroImage?: T;
  intro?: T;
  content?: T;
  schemaMarkup?:
    | T
    | {
        type?: T;
        headline?: T;
        faqItems?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  relatedArticles?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  focusKeyword?: T;
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
        slug?: T;
        credentials?: T;
        avatarUrl?: T;
      };
  slug?: T;
  source?: T;
  htmlContent?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  slug?: T;
  brandName?: T;
  manufacturerName?: T;
  jsonLd?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  credentials?: T;
  bio?: T;
  avatar?: T;
  website?: T;
  roleTitle?: T;
  affiliation?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Optional translated label. If empty, the default label will be used.
           */
          localizedLabel?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  logo?: (number | null) | Media;
  copyrightText?: string | null;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Optional translated label. If empty, the default label will be used.
           */
          localizedLabel?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  items?:
    | {
        label: string;
        link: {
          relationTo: 'pages';
          value: number | Page;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Site-wide Organization structured data (JSON-LD). Paste a JSON object. Example: @context, @type, name, url, logo, sameAs.
   */
  organizationJsonLd?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  sections: {
    title: string;
    items: {
      question: string;
      answer: string;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  /**
   * Optional. If empty, FAQPage JSON-LD will be auto-generated.
   */
  structuredData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              localizedLabel?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  copyrightText?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              localizedLabel?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  organizationJsonLd?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  sections?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
        id?: T;
      };
  structuredData?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}