name: Merge Main into STG & Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  merge-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Merge main → stg
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git fetch origin
          git checkout stg
          git merge origin/main --no-edit || true   # dacă există conflicte, job-ul pică
          git push origin stg

      - name: Deploy to Staging via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STG_HOST }}
          username: ${{ secrets.STG_USER }}
          key: ${{ secrets.STG_SSH_KEY }}
          script: |
            set -e
            cd /var/www/landing_page
            git fetch origin stg
            git merge origin/stg --no-edit
            bash deploy-stg.sh
