name: Deploy to Staging

on:
  push:
    branches:
      - stg

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Staging via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STG_HOST }}
          username: ${{ secrets.STG_USER }}
          key: ${{ secrets.STG_SSH_KEY }}
          script: |
            set -e
            cd /var/www/landing_page
            git fetch origin stg
            git reset --hard origin/stg
            docker compose -f docker-compose.stg.yml up -d --build
