name: Merge STG into PROD & Deploy

on:
  push:
    branches:
      - prod

permissions:
  contents: write

jobs:
  merge-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Merge stg → prod
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git fetch origin
          git checkout prod
          git merge origin/stg --no-edit
          git push origin prod

      - name: Deploy to Production via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd /var/www/landing_page
            bash deploy-prod.sh
