name: Deploy to Production

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout prod branch
        uses: actions/checkout@v4
        with:
          ref: prod
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure prod is fast-forward
        run: |
          git fetch origin prod
          git checkout prod
          git merge --ff-only origin/prod

      - name: Deploy to Production via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            set -e
            cd /var/www/landing_page
            bash deploy-prod.sh
