name: Sync Main to STG & Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync main → stg (force update)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git checkout -B stg origin/stg || git checkout -b stg
          git reset --hard origin/main
          git push origin stg --force

      - name: Deploy to Staging via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STG_HOST }}
          username: ${{ secrets.STG_USER }}
          key: ${{ secrets.STG_SSH_KEY }}
          script: |
            set -e
            cd /var/www/landing_page
            git fetch origin stg
            git reset --hard origin/stg
            docker compose -f docker-compose.stg.yml up -d --build
